name: flutter_boilerplate
description: Boilerplate for Starting Flutter Project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: 1.0.0
  keyboard_dismisser: 2.0.1
  resize: 1.0.0

flutter:
  uses-material-design: true
  # assets: