name: flutter_boilerplate
description: Boilerplate for Starting Flutter Project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: 1.0.0
  keyboard_dismisser: 2.0.1
  resize: 1.0.0
  flex_color_scheme: ^5.0.1
  auto_localization: ^2.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - env/

  # fonts:
    # - family: Lato
      # fonts:
        # - asset: assets/fonts/Lato-Regular.ttf


# run this command to change icon
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/transparent.png"
  image_path_android: "assets/icon/background.png"
  image_path_ios: "assets/icon/background.png"
  web:
    generate: false
    image_path: "assets/icon/transparent.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/transparent.png"
    icon_size: 256
  macos:
    generate: false
    image_path: "assets/icon/transparent.png"